import test from 'node:test';import assert from 'node:assert/strict';import {MockLanguageModelV4} from 'ai/test';
import {storeFixture,accountsFixture} from './database-fixture';import {defaultProfile,type Assessment,type Job} from '../packages/core/src/profile';import {ResearchTasks} from '../packages/core/src/research-tasks';import {investigateOpportunity,validatedInvestigation} from '../packages/core/src/investigator';import {listingDossier} from '../packages/core/src/research-memory';import {beginGeneration} from '../packages/core/src/ai-usage';import {Accounts} from '../packages/core/src/accounts';import type {Store} from '../packages/core/src/store';import type {InvestigationOutput} from '../packages/core/src/research-task-schema';
const companyUrl='https://example.test/about',quote='Example Company serves over two thousand customers.';
const job:Job={id:'resume',title:'Engineer',company:'Example Company',location:'Spain',url:'https://example.test/job',postedAt:null,description:'The role includes 20 hours per week and no on-call duties, working with a small product team.',firstSeen:'2026-01-01T00:00:00.000Z',lastSeen:'2026-01-01T00:00:00.000Z',assessment:null,status:'new',notifiedAt:null,evaluatedVersion:1};
const assessment:Assessment={score:70,eligibility:'uncertain',summary:'Hours and customers need investigation.',reasons:[],concerns:[],salaryEvidence:null,equityEvidence:null,founderPathEvidence:null};
const output:InvestigationOutput={questions:[{question:'What weekly hours does this specific role advertise?',topic:'Hours',scope:'job',claims:[{url:job.url,quote:'20 hours per week and no on-call duties',scope:'job',stance:'supports'}]},{question:'What customers does the company serve?',topic:'Customers',scope:'company',claims:[{url:companyUrl,quote,scope:'company',stance:'supports'}]}]};
function model(onCall:()=>void=()=>{},value:InvestigationOutput=output){return new MockLanguageModelV4({doGenerate:async()=>{onCall();return {content:[{type:'text' as const,text:JSON.stringify(value)},{type:'source' as const,sourceType:'url' as const,id:'company',url:companyUrl,title:'Company information'}],finishReason:{unified:'stop' as const,raw:undefined},usage:{inputTokens:{total:12,noCache:12,cacheRead:undefined,cacheWrite:undefined},outputTokens:{total:22,text:22,reasoning:undefined}},warnings:[]};}});}
async function retryNow(store:Store,version=1){const tasks=new ResearchTasks(store),task=(await tasks.get(job.id,version))!;task.nextAttemptAt='2020-01-01T00:00:00.000Z';await store.db.prepare('UPDATE research_tasks SET value=? WHERE user_id=? AND job_id=? AND profile_version=?').run(JSON.stringify(task),store.userId,job.id,version);}
async function setup(t:test.TestContext){const store=await storeFixture(t);await store.upsert(job);await store.assess(job.id,assessment,1);return store;}
test('transient source failure resumes the persisted plan and fetches only unchecked sources without a second generation',async t=>{
 const store=await setup(t),calls:string[]=[];let models=0;const mock=model(()=>models++);
 const first=await investigateOpportunity(store,job.id,{model:mock,read:async url=>{calls.push(url);return {url,status:url===companyUrl?503:200,html:`<p>${job.description}</p>`};}});assert.equal(first.status,'retry');assert.equal(first.verifiedEvidence,1);assert.equal((await store.job(job.id))?.research?.evidence.length,1);
 const tasks=new ResearchTasks(store);assert.equal(await tasks.ready((await store.job(job.id))!,1),false);assert.equal((await investigateOpportunity(store,job.id,{model:mock})).status,'deferred');
 await retryNow(store);const second=await investigateOpportunity(store,job.id,{model:mock,read:async url=>{calls.push(url);return {url,status:200,html:`<p>${quote}</p>`};}});assert.equal(second.status,'completed');assert.equal(second.resumed,true);assert.equal(second.verifiedEvidence,1);assert.equal(second.inputTokens,0);assert.equal(models,1);assert.deepEqual(calls,[job.url,companyUrl,companyUrl]);assert.equal((await store.job(job.id))?.research?.evidence.length,2);assert.equal((await store.job(job.id))?.research?.generationIds.length,1);assert.equal(Number((await store.db.prepare('SELECT count(*) AS n FROM ai_generations WHERE user_id=?').get(store.userId)).n),1);
});
test('failed sources stop after three attempts and manual retry preserves checked-plan work',async t=>{
 const store=await setup(t);await store.requestResearch(job.id);let models=0;const mock=model(()=>models++),read=async(url:string)=>({url,status:503,html:''});
 for(let attempt=1;attempt<=3;attempt++){const result=await investigateOpportunity(store,job.id,{model:mock,read});assert.equal(result.failed,attempt===3);if(attempt<3)await retryNow(store);}
 const saved=(await store.job(job.id))!;assert.equal(saved.researchTask?.status,'failed');assert.equal(saved.researchRequested,false);assert.equal(await new ResearchTasks(store).ready(saved,1),false);assert.equal(models,1);
 await store.requestResearch(job.id);const result=await investigateOpportunity(store,job.id,{model:mock,read:async url=>({url,status:200,html:`<p>${job.description} ${quote}</p>`})});assert.equal(result.status,'completed');assert.equal(models,1);assert.equal(result.resumed,true);
});
test('expired leases can be reclaimed but old workers cannot publish checkpoints, and newer requests survive completion',async t=>{
 const store=await setup(t);await store.requestResearch(job.id);const live=(await store.job(job.id))!,tasks=new ResearchTasks(store),old=(await tasks.claim(live,1))!;assert.equal(await tasks.claim(live,1),null);
 await store.db.prepare('UPDATE research_tasks SET value=? WHERE user_id=? AND job_id=? AND profile_version=1').run(JSON.stringify({...old,expiresAt:Date.now()-1}),store.userId,job.id);
 const next=(await tasks.claim(live,1))!;assert.notEqual(next.lease,old.lease);assert.equal(await tasks.checkpoint(old),false);assert.equal(await tasks.publish(old,listingDossier(job,assessment,1),false),false);
 await store.requestResearch(job.id);const freshId=(await store.job(job.id))?.researchRequestId;assert.notEqual(freshId,next.requestId);assert.equal(await tasks.publish(next,listingDossier(job,assessment,1),false),true);assert.equal((await store.job(job.id))?.researchRequested,true);assert.equal((await store.job(job.id))?.researchRequestId,freshId);
});
test('daily-budget deferral reserves no research call and does not consume retry attempts',async t=>{
 const store=await setup(t);await store.saveProfile({...defaultProfile,dailyEvaluationLimit:1});const version=(await store.profile()).version;await store.assess(job.id,assessment,version);await beginGeneration(store.userId,'ranking',1,new Accounts(store.db));
 await assert.rejects(investigateOpportunity(store,job.id,{model:model()}),/Daily AI call budget/);const task=await new ResearchTasks(store).get(job.id,version);assert.equal(task?.status,'waiting');assert.equal(task?.attempts,0);assert.equal(Number((await store.db.prepare('SELECT count(*) AS n FROM ai_generations WHERE user_id=?').get(store.userId)).n),1);
});
test('manual research retries remain eligible when ordinary scheduled discovery is paused and respect the minimum cadence',async t=>{
 const store=await setup(t);await store.requestResearch(job.id);await investigateOpportunity(store,job.id,{model:model(),read:async url=>({url,status:503,html:''})});await retryNow(store);await store.db.prepare('UPDATE state SET requested=0 WHERE user_id=?').run(store.userId);assert.equal((await store.profile()).profile.enabled,false);
 const claimed=await store.claim();assert.ok(claimed);await store.finish(claimed!,'completed',{discovered:0,evaluated:0,matched:0,inputTokens:0,outputTokens:0},null);assert.equal(await store.claim(),null);
});
test('research task checkpoints and company/job evidence stay scoped to the account and current profile',async t=>{
 const accounts=await accountsFixture(t),a=await accounts.signup({email:'task-a@example.test',password:'A private test password 2026'}),b=await accounts.signup({email:'task-b@example.test',password:'A private test password 2026'}),sa=await accounts.store(a.id),sb=await accounts.store(b.id);await sa.upsert(job);await sb.upsert(job);await sa.assess(job.id,assessment,1);
 const tasks=new ResearchTasks(sa),task=(await tasks.claim((await sa.job(job.id))!,1))!;assert.equal(await new ResearchTasks(sb).get(job.id,1),null);assert.equal(await new ResearchTasks(sb).checkpoint(task),false);await sa.saveProfile({...defaultProfile,objective:'Now I want a stable senior management position.'});assert.equal(await tasks.publish(task,listingDossier(job,assessment,1),false),false);await tasks.failure(task);assert.equal((await tasks.get(job.id,1))?.status,'cancelled');assert.equal((await sa.job(job.id))?.researchTask,null);
});
test('quality fixtures distinguish source support from plausible prose for pay, hours, ownership and workload goals',()=>{
 const cases=[
 {topic:'Salary',question:'What annual base salary is guaranteed?',bad:'Annual bonus can reach EUR 100000 depending on targets.',good:'Guaranteed annual base salary is EUR 90000.'},
 {topic:'Hours',question:'What weekly hours does this role require?',bad:'We support healthy work-life balance.',good:'This role requires 20 hours per week.'},
 {topic:'Ownership',question:'What actual ownership is offered in this role?',bad:'Join us as our first founding engineer.',good:'This role includes 1% equity in stock options.'},
 {topic:'Stress',question:'What on-call workload does this role require?',bad:'We are a calm and friendly team.',good:'This role has no on-call or weekend duties.'}
 ];
 for(const c of cases){const q={question:c.question,topic:c.topic,scope:'job' as const,claims:[{url:job.url,quote:c.bad,scope:'job' as const,stance:'supports' as const}]};const previous=listingDossier(job,assessment,1),bad=validatedInvestigation({questions:[q]},job,previous,new Map([[job.url,{text:c.bad,retrievedAt:job.firstSeen}]]),new Set(),'fixture-generation','en');assert.equal(bad.answered,0,c.topic);assert.equal(bad.unresolved,1,c.topic);
 const good=validatedInvestigation({questions:[{...q,claims:[{...q.claims[0],quote:c.good}]}]},job,previous,new Map([[job.url,{text:c.good,retrievedAt:job.firstSeen}]]),new Set(),'fixture-generation','en');assert.equal(good.answered,1,c.topic);assert.equal(good.dossier.questions[0].answer,c.good);}
});
test('a checked company header establishes a name receipt without synthesizing quotes across fragments',async t=>{
 const store=await setup(t),excerpt='Our product serves over two thousand customers.',companyOnly:InvestigationOutput={questions:[{...output.questions[1],claims:[{...output.questions[1].claims[0],quote:excerpt}]}]};const result=await investigateOpportunity(store,job.id,{model:model(()=>{},companyOnly),read:async url=>({url,status:200,html:`<h1>Example Company</h1><p>${excerpt}</p>`})});assert.equal(result.answered,1);
 const previous=listingDossier(job,assessment,1);const fragmentOutput:InvestigationOutput={questions:[{question:'What customers does the company serve?',topic:'Customers',scope:'company',claims:[{url:companyUrl,quote:'Customers use our reliable product',scope:'company',stance:'supports'}]}]};
 const checked=validatedInvestigation(fragmentOutput,job,previous,new Map([[companyUrl,{text:'Customers use our reliable product',quotes:['Customers use our','reliable product'],employerNamed:true,retrievedAt:job.firstSeen}]]),new Set([companyUrl]),'fixture-generation','en');assert.equal(checked.verifiedEvidence,0);
});
test('profile changes before plan persistence leave a failed generation instead of an unfinished reservation',async t=>{
 const store=await setup(t),mock=model(),generate=mock.doGenerate;mock.doGenerate=async options=>{await store.saveProfile({...defaultProfile,objective:'A different goal after the model started its investigation.'});return generate(options);};
 await assert.rejects(investigateOpportunity(store,job.id,{model:mock}),/profile changed/);assert.equal((await store.db.prepare('SELECT status FROM ai_generations WHERE user_id=?').get(store.userId)).status,'failed');assert.equal((await new ResearchTasks(store).get(job.id,1))?.status,'cancelled');assert.equal((await store.job(job.id))?.research?.generationIds.length,0);
});
test('closed manual research tasks do not repeatedly wake paused accounts or publish evidence',async t=>{
 const store=await setup(t);await store.requestResearch(job.id);const tasks=new ResearchTasks(store),task=(await tasks.claim((await store.job(job.id))!,1))!;await store.verify(job.id,{status:'closed',checkedAt:new Date().toISOString(),applicationUrl:null,note:'Listing closed.'});assert.equal(await tasks.publish(task,listingDossier(job,assessment,1),false),false);await tasks.failure(task);assert.equal((await tasks.get(job.id,1))?.status,'cancelled');await store.db.prepare('UPDATE state SET requested=0 WHERE user_id=?').run(store.userId);assert.equal(await store.claim(),null);
});
test('a worker crash on the final lease attempt pauses the task instead of waking indefinitely',async t=>{
 const store=await setup(t);await store.requestResearch(job.id);const tasks=new ResearchTasks(store),task=(await tasks.claim((await store.job(job.id))!,1))!;await store.db.prepare('UPDATE research_tasks SET value=? WHERE user_id=? AND job_id=? AND profile_version=1').run(JSON.stringify({...task,attempts:3,expiresAt:Date.now()-1}),store.userId,job.id);assert.equal(await tasks.claim((await store.job(job.id))!,1),null);assert.equal((await tasks.get(job.id,1))?.status,'failed');assert.equal((await store.job(job.id))?.researchRequested,false);assert.equal(await tasks.ready((await store.job(job.id))!,1),false);
});
test('repeating the same supported quote cannot inflate the verified evidence count',()=>{
 const q=output.questions[0],previous=listingDossier(job,assessment,1),result=validatedInvestigation({questions:[{...q,claims:[q.claims[0],q.claims[0]]},{...q,question:'Does the same listing state these weekly hours?'}]},job,previous,new Map([[job.url,{text:job.description!,retrievedAt:job.firstSeen}]]),new Set(),'fixture-generation','en');assert.equal(result.verifiedEvidence,1);assert.equal(result.dossier.evidence.length,1);
});
