ALTER TABLE runs ADD COLUMN IF NOT EXISTS discovery TEXT;
CREATE TABLE IF NOT EXISTS discovery_state (
 user_id TEXT PRIMARY KEY REFERENCES accounts(id) ON DELETE CASCADE,
 scope TEXT NOT NULL,
 value TEXT NOT NULL
);
