'use client';
import type {Job} from '@core/profile';import type {ResearchStats} from '@core/research-task-schema';import {useI18n} from './i18n';
export function ResearchProgress({job}:{job:Job}){
 const {t,date}=useI18n(),task=job.researchTask;if(!task)return null;
 return <p role="status" className="footnote">{job.status==='dismissed'||job.duplicateOf||job.verification?.status==='closed'||job.assessment?.eligibility==='ineligible'?t('Research stopped because the profile or opportunity changed.'):task.status==='running'?t('Research is in progress. Checked sources are saved along the way.'):task.status==='waiting'?t('Research will resume after {date}. Attempt {attempt} of 3.',{date:date(task.nextAttemptAt),attempt:task.attempts}):task.status==='failed'?t('Research paused after three attempts. Saved evidence is available; request research to retry.'):task.status==='cancelled'?t('Research stopped because the profile or opportunity changed.'):t('This investigation finished. Any unanswered questions remain visible below.')}</p>;
}
export function ResearchRunReport({stats}:{stats:ResearchStats}){
 const {t,number}=useI18n();return <details className="job-details"><summary>{t('Investigation coverage and outcomes')}</summary><p>{t('Investigations: {attempted}; completed: {completed}; resumed: {resumed}.',{attempted:number(stats.attempted),completed:number(stats.completed),resumed:number(stats.resumed)})}</p><p>{t('Checked excerpts: {evidence}; questions with sources: {answered}; unresolved or conflicting: {unresolved}.',{evidence:number(stats.verifiedEvidence),answered:number(stats.answered),unresolved:number(stats.unresolved)})}</p><p>{t('Retries scheduled: {retry}; attempts failed: {failed}.',{retry:number(stats.retryScheduled),failed:number(stats.failed)})}</p><p className="footnote">{t(({disabled:'Goal research is switched off.',unavailable:'Web research access is not configured.',daily_budget:'Daily AI call budget reached. Try again after midnight UTC.',time_budget:'The run reached its time limit.',opportunity_limit:'The run reached its two-opportunity research limit.',finished:'Research processing ended for this run.'} as const)[stats.stopReason])}</p><p className="footnote">{t('These counts describe checked sources and remaining uncertainty. They do not measure application or hiring outcomes.')}</p></details>;
}
