'use client';
import {useI18n,LanguageSelect} from './i18n';
import { useState } from 'react';
import type { Profile } from '@core/profile';
import { defaultStrategy, type Strategy } from '@core/strategy';
import type { StrategyProposal } from '@core/import-strategy';
const key=(prefix:string)=>`${prefix}_${crypto.randomUUID().replaceAll('-','').slice(0,16)}`;
function UnknownOptions(){
 const {t,locale,date,number,message:localizeMessage}=useI18n();
return <><option value="research">{t("Keep for research")}</option><option value="exclude">{t("Exclude until evidenced")}</option><option value="allow">{t("Keep; clarify later")}</option></>;}
export default function StrategyEditor({profile,onChange}:{profile:Profile;onChange:(value:Profile)=>void}){
 const {t,locale,date,number,message:localizeMessage}=useI18n();

 const strategy=profile.strategy;
 const update=(value:Partial<Strategy>)=>onChange({...profile,strategy:{...strategy,...value}});
 const [text,setText]=useState('');const [proposal,setProposal]=useState<StrategyProposal|null>(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 return <>
 <section className="panel"><h2>{t("Import your search strategy")}</h2><p className="muted">{t("Bring an existing Markdown brief. Review the proposed settings before adding them to your profile. Your CV stays separate.")}</p>
 <label>{t("Strategy document")}<input type="file" accept=".md,.txt,text/plain,text/markdown" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>160000){setMessage(t("Use a document under 160 KB."));return;}const value=await file.text();if(value.length>40000){setMessage(t("Use up to 40,000 characters."));return;}setText(value);setProposal(null);}}/></label>
 <label>{t("Or paste your brief")}<textarea rows={5} value={text} maxLength={40000} onChange={e=>{setText(e.target.value);setProposal(null);}}/></label>
 <button type="button" className="button secondary" disabled={busy||text.length<100} onClick={async()=>{setBusy(true);setMessage('');setProposal(null);try{const response=await fetch('/api/strategy',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text})});const result=await response.json();if(!response.ok)throw new Error(result.error);setProposal(result.proposal);}catch(e){setMessage(e instanceof Error?e.message:t("Import failed."));}finally{setBusy(false);}}}>{busy?t("Preparing draft…"):t("Prepare settings for review")}</button>
 {message&&<p role="status">{message}</p>}
 {proposal&&<div className="proposal"><h3>{t("Review proposed settings")}</h3><dl><dt>{t("Goal")}</dt><dd>{proposal.objective}</dd><dt>{t("Roles")}</dt><dd>{proposal.titles.join(' · ')}</dd><dt>{t("Locations")}</dt><dd>{proposal.locations.join(' · ')||t("Worldwide")}</dd><dt>{t("Salary / equity")}</dt><dd>{proposal.salaryExpectation||t("Unspecified")} / {proposal.equityExpectation||t("Unspecified")}</dd><dt>{t("Constraints")}</dt><dd>{proposal.constraints||t("None")}</dd><dt>{t("Citizenships / relocation")}</dt><dd>{proposal.strategy.citizenships.join(', ')||t("Unspecified")} / {proposal.strategy.relocation||t("Unspecified")}</dd><dt>{t("Posting window")}</dt><dd>{proposal.postedWithinDays} {t("days; unknown dates")} {proposal.includeUnknownDates?t('included'):t('excluded')}</dd></dl>
 <h3>{t("Work access")}</h3>{proposal.strategy.workAccess.map(r=><p key={r.country}>{r.country}: {r.access==='authorized'?t("Existing work rights"):t('Sponsorship needed; unknown → {action}',{action:t(r.unknownSponsorship)})}</p>)}
 <h3>{t("Requirements")}</h3>{proposal.strategy.requirements.map(r=><p key={r.id}><strong>{r.label}</strong>: {r.instruction} {t("· Unknown:")} {t(r.unknown)}</p>)}
 <h3>{t("Scoring")}</h3>{proposal.strategy.groups.map(g=><div key={g.id}><strong>{g.label} {t("— weight")} {g.weight}</strong>{g.criteria.map(c=><p key={c.id}>{c.label} {t("— weight")} {c.weight}: {c.rubric}</p>)}</div>)}
 {proposal.strategy.caps.map((c,i)=><p key={i}>{t("Cap:")} {proposal.strategy.groups.flatMap(g=>g.criteria).find(r=>r.id===c.criterionId)?.label} ≤ {c.atOrBelow} {t("limits the overall score to")} {c.maximum}/100.</p>)}
 {!!proposal.warnings.length&&<><h3>{t("Needs your attention")}</h3><ul>{proposal.warnings.map((w,i)=><li key={i}>{w}</li>)}</ul></>}
 <button type="button" className="button primary" onClick={()=>{const {warnings,...settings}=proposal;onChange({...profile,...settings});setProposal(null);setMessage(t("Draft added to the form. Review the fields below, then save your search profile."));}}>{t("Use this draft in my profile")}</button><button type="button" className="text-button" onClick={()=>setProposal(null)}>{t("Discard draft")}</button></div>}
 </section>
 <section className="panel"><h2>{t("Where you can work")}</h2><p className="muted">{t("Enter your known work rights. A passport alone does not automatically establish access here. Search locations above control discovery; these rules control qualification.")}</p>
 <label>{t("Citizenships")} <span className="optional">{t("One per line")}</span><textarea rows={2} value={strategy.citizenships.join('\n')} onChange={e=>update({citizenships:e.target.value.split('\n')})}/></label>
 <label>{t("Relocation preferences")}<textarea rows={2} value={strategy.relocation} maxLength={1000} onChange={e=>update({relocation:e.target.value})}/></label>
 {strategy.workAccess.map((rule,i)=><div className="strategy-row" key={i}><label>{t("Country code")}<input aria-label={t('Country code {count}',{count:i+1})} value={rule.country} maxLength={2} placeholder="US" onChange={e=>update({workAccess:strategy.workAccess.map((r,n)=>n===i?{...r,country:e.target.value.toUpperCase()}:r)})}/></label><label>{t("Work access")}<select value={rule.access} onChange={e=>update({workAccess:strategy.workAccess.map((r,n)=>n===i?{...r,access:e.target.value as typeof r.access}:r)})}><option value="authorized">{t("I already have work rights")}</option><option value="sponsorship">{t("I need sponsorship")}</option></select></label>{rule.access==='sponsorship'&&<label>{t("If sponsorship is unstated")}<select value={rule.unknownSponsorship} onChange={e=>update({workAccess:strategy.workAccess.map((r,n)=>n===i?{...r,unknownSponsorship:e.target.value as typeof r.unknownSponsorship}:r)})}><UnknownOptions/></select></label>}<button type="button" className="text-button" onClick={()=>update({workAccess:strategy.workAccess.filter((_,n)=>n!==i)})}>{t("Remove country")}</button></div>)}
 <button type="button" className="button secondary" disabled={strategy.workAccess.length>=40} onClick={()=>update({workAccess:[...strategy.workAccess,{country:'',access:'sponsorship',unknownSponsorship:'research'}]})}>{t("Add country rule")}</button>
 <p className="footnote">{t("Use two-letter country codes, such as MX, US, GB or DE. With rules enabled, an unmatched or unclear location is held for research. These are your declared requirements, not an immigration determination.")}</p>
 </section>
 <section className="panel"><h2>{t("Must-have requirements")}</h2><p className="muted">{t("Optional gates that a high score cannot override. Leave empty if ordinary job-fit scoring is enough.")}</p>
 {strategy.requirements.map((rule,i)=><div className="strategy-block" key={rule.id}><label>{t("Requirement name")}<input value={rule.label} maxLength={120} onChange={e=>update({requirements:strategy.requirements.map((r,n)=>n===i?{...r,label:e.target.value}:r)})}/></label><label>{t("What evidence qualifies?")}<textarea value={rule.instruction} minLength={10} maxLength={2000} onChange={e=>update({requirements:strategy.requirements.map((r,n)=>n===i?{...r,instruction:e.target.value}:r)})}/></label><label>{t("If evidence is missing")}<select value={rule.unknown} onChange={e=>update({requirements:strategy.requirements.map((r,n)=>n===i?{...r,unknown:e.target.value as typeof r.unknown}:r)})}><UnknownOptions/></select></label><button type="button" className="text-button" onClick={()=>update({requirements:strategy.requirements.filter((_,n)=>n!==i)})}>{t("Remove requirement")}</button></div>)}
 <button type="button" className="button secondary" disabled={strategy.requirements.length>=10} onClick={()=>update({requirements:[...strategy.requirements,{id:key('requirement'),label:t('New requirement'),instruction:t('Describe the concrete evidence you require in a qualifying role.'),unknown:'research'}]})}>{t("Add requirement")}</button>
 </section>
 <details className="panel"><summary><h2>{t("Your scoring priorities")}</h2></summary><p className="muted">{t("Each criterion is assessed from 1–5. Group and criterion weights are relative; the app calculates the final score. Missing evidence is shown as unknown and contributes 1 conservatively.")}</p>
 {strategy.groups.map((group,i)=><div className="strategy-block" key={group.id}><div className="field-grid"><label>{t("Group name")}<input value={group.label} maxLength={100} onChange={e=>update({groups:strategy.groups.map((g,n)=>n===i?{...g,label:e.target.value}:g)})}/></label><label>{t("Group weight")}<input type="number" min={1} max={100} value={group.weight} onChange={e=>update({groups:strategy.groups.map((g,n)=>n===i?{...g,weight:Number(e.target.value)}:g)})}/></label></div>
 {group.criteria.map((criterion,j)=><div className="criterion" key={criterion.id}><div className="field-grid"><label>{t("Criterion name")}<input value={criterion.label} maxLength={100} onChange={e=>update({groups:strategy.groups.map((g,n)=>n===i?{...g,criteria:g.criteria.map((c,m)=>m===j?{...c,label:e.target.value}:c)}:g)})}/></label><label>{t("Criterion weight")}<input type="number" min={1} max={100} value={criterion.weight} onChange={e=>update({groups:strategy.groups.map((g,n)=>n===i?{...g,criteria:g.criteria.map((c,m)=>m===j?{...c,weight:Number(e.target.value)}:c)}:g)})}/></label></div><label>{t("Scoring rubric")}<textarea rows={3} value={criterion.rubric} maxLength={1500} onChange={e=>update({groups:strategy.groups.map((g,n)=>n===i?{...g,criteria:g.criteria.map((c,m)=>m===j?{...c,rubric:e.target.value}:c)}:g)})}/></label><button type="button" className="text-button" disabled={group.criteria.length===1} onClick={()=>update({groups:strategy.groups.map((g,n)=>n===i?{...g,criteria:g.criteria.filter((_,m)=>m!==j)}:g),caps:strategy.caps.filter(c=>c.criterionId!==criterion.id)})}>{t("Remove criterion")}</button></div>)}
 <button type="button" className="button secondary" disabled={group.criteria.length>=8} onClick={()=>update({groups:strategy.groups.map((g,n)=>n===i?{...g,criteria:[...g.criteria,{id:key('criterion'),label:t('New criterion'),weight:20,rubric:t('1: poor fit; 3: partial fit; 5: strong fit. Add concrete evidence anchors.')}]}:g)})}>{t("Add criterion")}</button> <button type="button" className="text-button" disabled={strategy.groups.length===1} onClick={()=>update({groups:strategy.groups.filter((_,n)=>n!==i),caps:strategy.caps.filter(c=>!group.criteria.some(r=>r.id===c.criterionId))})}>{t("Remove group")}</button></div>)}
 <button type="button" className="button secondary" disabled={strategy.groups.length>=4} onClick={()=>update({groups:[...strategy.groups,{id:key('group'),label:t('New group'),weight:35,criteria:[{...defaultStrategy.groups[0].criteria[0],label:t(defaultStrategy.groups[0].criteria[0].label),rubric:t(defaultStrategy.groups[0].criteria[0].rubric),id:key('criterion')}]}]})}>{t("Add scoring group")}</button>
 <h3 className="subheading">{t("Score caps")}</h3>{strategy.caps.map((cap,i)=><div className="strategy-row" key={i}><label>{t("Criterion")}<select value={cap.criterionId} onChange={e=>update({caps:strategy.caps.map((c,n)=>n===i?{...c,criterionId:e.target.value}:c)})}>{strategy.groups.flatMap(g=>g.criteria).map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select></label><label>{t("When score is at most")}<input type="number" min={1} max={5} step={0.1} value={cap.atOrBelow} onChange={e=>update({caps:strategy.caps.map((c,n)=>n===i?{...c,atOrBelow:Number(e.target.value)}:c)})}/></label><label>{t("Cap overall score /100")}<input type="number" min={0} max={100} value={cap.maximum} onChange={e=>update({caps:strategy.caps.map((c,n)=>n===i?{...c,maximum:Number(e.target.value)}:c)})}/></label><button type="button" className="text-button" onClick={()=>update({caps:strategy.caps.filter((_,n)=>n!==i)})}>{t("Remove cap")}</button></div>)}
 <button type="button" className="button secondary" disabled={strategy.caps.length>=8} onClick={()=>update({caps:[...strategy.caps,{criterionId:strategy.groups[0].criteria[0].id,atOrBelow:1,maximum:70}]})}>{t("Add score cap")}</button>
 </details>
 </>;
}
