'use client';
import {useI18n,LanguageSelect} from './i18n';
import { useState } from 'react';
import { trackingSchema, type Job } from '@core/profile';
export default function TrackingEditor({job,refresh}:{job:Job;refresh:()=>Promise<void>}){
 const {t,locale,date,number,message:localizeMessage}=useI18n();

 const [draft,setDraft]=useState(()=>trackingSchema.parse(job.tracking||{}));const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 const evaluation=job.assessment?.evaluation;const verification=job.verification;
 return <details className="job-details"><summary>{t("Track this opportunity and inspect evidence")} <span>+</span></summary>
 {job.duplicateOf&&<button type="button" className="button secondary" disabled={busy} onClick={async()=>{setBusy(true);try{const response=await fetch(`/api/jobs/${encodeURIComponent(job.id)}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({distinct:true})});if(!response.ok)throw new Error();await refresh();setMessage(t("Marked as a separate opportunity."));}catch{setMessage(t("Could not update duplicate status."));}finally{setBusy(false);}}}>{t("This is a separate opportunity")}</button>}
 <div className="details-grid"><div><h3>{t("Application route")}</h3><p>{verification?.status==='open'?t("Application form reachable"):verification?.status==='closed'?t("Listing closed"):t("Not verified")}</p><p>{verification?.note&&localizeMessage(verification.note)}</p><p>{t("Last checked:")} {verification?date(verification.checkedAt):t("Never")}{verification&&Date.now()-Date.parse(verification.checkedAt)>14*86400000?t(" · Recheck due"):''}</p><p>{t("Posted:")} {job.postedAt?date(job.postedAt,false):t("Unknown")} {t("· Added:")} {date(job.firstSeen,false)}</p>
 {verification?.applicationUrl&&<a href={verification.applicationUrl} target="_blank" rel="noopener noreferrer" className="text-button">{t("Open application route ↗")}</a>}
 <button type="button" className="button secondary" disabled={busy} onClick={async()=>{setBusy(true);setMessage('');try{const response=await fetch(`/api/jobs/${encodeURIComponent(job.id)}/verify`,{method:'POST'});const result=await response.json();if(!response.ok)throw new Error(result.error);await refresh();setMessage(result.verification.note);}catch(e){setMessage(e instanceof Error?e.message:t("Check failed."));}finally{setBusy(false);}}}>{busy?t("Working…"):t("Check application link")}</button>
 {evaluation&&<><h3 className="subheading">{t("Scoring calculation")}</h3>{evaluation.groups.map(g=><p key={g.id}>{g.label}: {number(g.score)}/5</p>)}{evaluation.components.map(c=><p key={c.id}><strong>{c.label}: {c.score===null?t("Unknown"):number(c.score)}</strong><br/>{localizeMessage(c.reason)}{c.evidence&&<><br/><q>{c.evidence}</q></>}</p>)}<h3 className="subheading">{t("Qualification evidence")}</h3>{evaluation.gates.map(g=><p key={g.id}><strong>{g.label}: {t(g.result)}</strong><br/>{localizeMessage(g.reason)}{g.evidence&&<><br/><q>{g.evidence}</q></>}</p>)}{evaluation.access.map((a,i)=><p key={i}>{a.country}{t(": sponsorship")} {t(a.sponsorship)} · {t(a.action)}{a.evidence&&<><br/><q>{a.evidence}</q></>}</p>)}</>}
 </div><form onSubmit={async e=>{e.preventDefault();setBusy(true);setMessage('');try{const response=await fetch(`/api/jobs/${encodeURIComponent(job.id)}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({tracking:draft})});const result=await response.json();if(!response.ok)throw new Error(result.error);await refresh();setMessage(t("Tracking saved."));}catch(e){setMessage(e instanceof Error?e.message:t("Could not save."));}finally{setBusy(false);}}}>
 <label>{t("Application stage")}<select value={draft.stage} onChange={e=>setDraft({...draft,stage:e.target.value as typeof draft.stage})}>{[['not_recorded',t("Not recorded")],['not_applied',t("Not applied")],['applied',t("Applied")],['interviewing',t("Interviewing")],['offer',t("Offer")],['rejected',t("Rejected")],['withdrawn',t("Withdrawn")]].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>
 <label>{t("My recommendation")}<select value={draft.recommendation} onChange={e=>setDraft({...draft,recommendation:e.target.value as typeof draft.recommendation})}>{[['automatic',t("Use evaluation")],['apply',t("Apply")],['apply_verify',t("Apply + verify")],['research',t("Research")],['exclude',t("Exclude")]].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><small>{t("Failed requirements and closed listings still prevent an application recommendation.")}</small></label>
 <label>{t("Next action")}<textarea value={draft.nextAction} maxLength={1500} onChange={e=>setDraft({...draft,nextAction:e.target.value})}/></label>
 <label>{t("Follow-up date")}<input type="date" value={draft.followUp} onChange={e=>setDraft({...draft,followUp:e.target.value})}/></label>
 <label>{t("Notes")}<textarea value={draft.notes} maxLength={8000} onChange={e=>setDraft({...draft,notes:e.target.value})}/></label>
 <button className="button primary" disabled={busy}>{t("Save tracking")}</button>
 </form></div>{message&&<p role="status">{message}</p>}
 </details>;
}
